# Generated by Django 4.2 on 2023-05-31 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtiger', '0002_category_menuitem_ordermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name_plural': 'Menu Item'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name_plural': 'Order '},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='fooditem',
        ),
    ]
